spring:
  config.import: classpath:common.yml
  application.name: ms-pedidos360-orders
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
server.port: 8081
catalog.url: ${CATALOG_URL:http://localhost:8082}
